services:
  Apps.Panda.Backend.Controllers.HealthCheckController:
    class: ../../controllers/HealthCheck/HealthCheckController
    arguments: []

  Apps.Panda.Backend.Controllers.EventCategoryPostController:
    class: ../../controllers/EventCategory/EventCategoryPostController
    arguments: ['@Panda.EventCategory.application.EventCategoryCreator']
