services:
  Panda.TypeOrmConfig:
    factory:
      class: '../../../../../Contexts/Panda/Shared/infrastructure/persistence/postgres/TypeOrmConfigFactory'
      method: 'createConfig'

  Panda.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/persistence/TypeOrmClientFactory
      method: 'createClient'
    arguments: ['@Panda.TypeOrmConfig', '@Shared.Logger']

  Panda.EventCategory.domain.EventCategoryRepository:
    class: ../../../../../Contexts/Panda/EventsCategory/infrastructure/repositories/TypeOrmEventCategoryRepository
    arguments: ['@Panda.ConnectionManager']

  Panda.EventCategory.application.EventCategoryCreator:
    class: ../../../../../Contexts/Panda/EventsCategory/application/EventCategoryCreator
    arguments: ['@Panda.EventCategory.domain.EventCategoryRepository']
