export const MESSAGE_CODES = {
  SUCCESS: 'SUCCESS',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  CATEGORY_EVENT: {
    INVALID_CATEGORY_ID: 'INVALID_CATEGORY_ID'
  },
  SHARED: {
    INVALID_ID: 'INVALID_ID',
    INVALID_STATE: 'INVALID_STATE',
    INVALID_DATE: 'INVALID_DATE',
    INVALID_NAME: 'INVALID_NAME',
    INVALID_PRICE: 'INVALID_PRICE',
    INVALID_QUANTITY: 'INVALID_QUANTITY',
    INVALID_DESCRIPTION: 'INVALID_DESCRIPTION'
  },
  EVENT_CATEGORY: {
    INVALID_EVENT_CATEGORY_ID: 'INVALID_EVENT_CATEGORY_ID',
    CATEGORY_ID_MUST_BE_STRING: 'CATEGORY_ID_MUST_BE_STRING'
  }
};
